apiVersion: v1
kind: Service
metadata:
  name: nodeport-demo
  labels:
    env: prod
    app: nginx
spec:
  selector:
    app: nginx
    env: prod
  type: NodePort
  ports:
    - nodePort: 32456
      protocol: TCP
      port: 80
      targetPort: 80
