apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-cm
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 443
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: tls-volume
          mountPath: /etc/nginx/ssl
  volumes:
    - name: html
      configMap:
        name: nginx-config
    - name: nginx-conf
      configMap:
        name: nginx-config
    - name: tls-volume
      secret:
        secretName: tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-cm
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443  # optional; must be in the range 30000-32767
