apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-demo
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: lima-rancher-desktop
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80