apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-demo
  labels:
    app: nginx
    env: prod
spec:
  serviceName: headless-service # Keep for dns resolving
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      env: prod
  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      containers:
      - name: nginx
        #image: nginx:1.14.2
        image: madawa/wso2-demo
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html-www
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: headless-service
  labels:
    app: nginx
    env: prod
spec:
  ports:
    - port: 80
      targetPort: 80
  clusterIP: None # Headless Service <pod-name>.<svc-name>.<namespace>.svc.cluster.local
  selector:
    app: nginx
    env: prod
